const filterOptionsData = [
  { name: 'Normal', classString: 'filter-normal' },
  { name: '1977', classString: 'filter-1977' },
  { name: 'Aden', classString: 'filter-aden' },
  { name: 'Amaro', classString: 'filter-amaro' },
  { name: 'Ashby', classString: 'filter-ashby' },
  { name: 'Brannan', classString: 'filter-brannan' },
  { name: 'Brooklyn', classString: 'filter-brooklyn' },
  { name: 'Charmes', classString: 'filter-charmes' },
  { name: 'Clarendon', classString: 'filter-clarendon' },
  { name: 'Crema', classString: 'filter-crema' },
  { name: 'Dogpatch', classString: 'filter-dogpatch' },
  { name: 'Earlybird', classString: 'filter-earlybird' },
  { name: 'Gingham', classString: 'filter-gingham' },
  { name: 'Ginza', classString: 'filter-ginza' },
  { name: 'Hefe', classString: 'filter-hefe' },
  { name: 'Helena', classString: 'filter-helena' },
  { name: 'Hudson', classString: 'filter-hudson' },
  { name: 'Inkwell', classString: 'filter-inkwell' },
  { name: 'Kelvin', classString: 'filter-kelvin' },
  { name: 'Juno', classString: 'filter-juno' },
  { name: 'Lark', classString: 'filter-lark' },
  { name: 'Lo-Fi', classString: 'filter-lofi' },
  { name: 'Ludwig', classString: 'filter-ludwig' },
  { name: 'Maven', classString: 'filter-maven' },
  { name: 'Mayfair', classString: 'filter-mayfair' },
  { name: 'Moon', classString: 'filter-moon' },
  { name: 'Nashville', classString: 'filter-nashville' },
  { name: 'Perpetua', classString: 'filter-perpetua' },
  { name: 'Poprocket', classString: 'filter-poprocket' },
  { name: 'Reyes', classString: 'filter-reyes' },
  { name: 'Rise', classString: 'filter-rise' },
  { name: 'Sierra', classString: 'filter-sierra' },
  { name: 'Skyline', classString: 'filter-skyline' },
  { name: 'Slumber', classString: 'filter-slumber' },
  { name: 'Stinson', classString: 'filter-stinson' },
  { name: 'Sutro', classString: 'filter-sutro' },
  { name: 'Toaster', classString: 'filter-toaster' },
  { name: 'Valencia', classString: 'filter-valencia' },
  { name: 'Vesper', classString: 'filter-vesper' },
  { name: 'Walden', classString: 'filter-walden' },
  { name: 'Willow', classString: 'filter-willow' },
  { name: 'X-Pro II', classString: 'filter-xpro-ii' },
];

export default filterOptionsData;
